export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const GET_ALL_MISSIONS = 'GET_ALL_MISSIONS';
export const GET_ALL_MISSIONS_SUCCESS = 'GET_ALL_MISSIONS_SUCCESS';
